### ISSUE TITLE
Unable to find template

### ISSUE THREAD

**Issue by Galixte** [nickv-phpbb/phpbb-ext-newspage#118]
Hi,

why my styles on my board, the child styles of prosilver like PBTech, proFormell, prosilver SE or we_universal  have this error on News page ?

```
Unable to find template "event/viewtopic_body_avatar_before.html" (looked into: ) in "viewtopic_postrow.html" at line 9.
```

With subsilver2 the error is different but i guess it's normal because there are not file about this in extension:

```
Unable to find template "newspage_body.html" (looked into: ./styles/subsilver2/template, ./styles/subsilver2/theme).
```

Could you fix it ?

**Comment by nickvergessen** [comment]
Sorry I don't support subsilver2 and subsilver2 based styles.

About the first error, that doesn't look like a bug with the newspage. More like an other extension that tries to do something with the topic rows. Do you have something like that installed?

**Comment by Galixte** [comment]
Yes a lot, i'll do more tests

**Comment by Galixte** [comment]
Hi,

it’s OK for me, problem of upload file i suppose. Thanks.
