### ISSUE TITLE
Regression from #126 broke the mini-profile on viewtopic.php

### ISSUE THREAD

**Issue by Galixte** [nickv-phpbb/phpbb-ext-newspage#128]
Hi,

i’m not sure, but since your PR 126: https://github.com/nickv-phpbb/phpbb-ext-newspage/pull/126 the mini-profile doesn’t show on viewtopic.

**Comment by nickvergessen** [comment]
Thanks for testing! :grinning:

**Comment by Galixte** [comment]
Thanks you ;)
