### ISSUE TITLE
Responsive mode with Show user information setting

### ISSUE THREAD

**Issue by Galixte** [nickv-phpbb/phpbb-ext-newspage#134]
Hi @nickvergessen,

in responsive mode, if i have activated the setting: “Show user information
Avatar, Profile Fields, etc.” the avatar, rank and the username are still displayed, like this: http://img11.hostingpics.net/pics/352893Capture.jpg.

**Comment by nickvergessen** [comment]
Well wwe cant display, what phpbb itself hides

**Comment by Galixte** [comment]
Sorry @nickvergessen, i wanted to say:

in responsive mode, if i have DISABLED the setting: “Show user information
Avatar, Profile Fields, etc.” the avatar, rank and the username are still displayed, like this: http://img11.hostingpics.net/pics/352893Capture.jpg.
