### ISSUE TITLE
soft-deleted comments will be counted

### ISSUE THREAD

**Issue by nachtelb** [nickv-phpbb/phpbb-ext-newspage#45]
Hello nickvergessen, thanks for this great extension. At present soft-deleted comments are counted. You See: Comments: 1 but the Comments will be empty...

**Comment by nickvergessen** [comment]
They should only be counted, if you have the permissions to see them.
Can you check that?

**Comment by nickvergessen** [comment]
What I just found out is, that the news itself is now counted as a comment, because the number is not the replies anymore, but all posts. So I will fix that. Thanks for notifying.
