### ISSUE TITLE
feature-request - make choosen forums invisible yes/no

### ISSUE THREAD

**Issue by nachtelb** [nickv-phpbb/phpbb-ext-newspage#53]
I dont know if its possible to overwrite the forum-permissions by an extension. If it is possible, it would be really fine if you give the option in the ACP:

Make choosen forums invisible in forum-index yes/no

In this case the forum-permission "can see forum" should be overwritten to "never" for all users (except admin&mod).

**Comment by nickvergessen** [comment]
You can already do that, and it is unrelated to newspage.

Close #53

Am 30.10.2013 20:06, schrieb Bernhard:
