### ISSUE TITLE
attachment off - picture inline - filename shows up 

### ISSUE THREAD

**Issue by nachtelb** [nickv-phpbb/phpbb-ext-newspage#56]
I dont know if this is wanted, but it doesnt look good. When attachments are set to not show up on newspage and there is a picture inline the filename shows up.
![filename](https://f.cloud.github.com/assets/538411/1440565/0ed822f2-419c-11e3-8c16-102ad23b8705.jpg)

**Comment by nickvergessen** [comment]
Hmm I think inline attachments should always be displayed, because I can not really change the way the parser works and filter out the file name.
