### ISSUE TITLE
Archive-Link doesnt find News

### ISSUE THREAD

**Issue by nachtelb** [nickv-phpbb/phpbb-ext-newspage#61]
The Archive-Link shows 4 News in October. When i click on this Link no News will be found.

![archive](https://f.cloud.github.com/assets/538411/1502191/3dd6b4fe-4897-11e3-9667-dfd6a1045bb3.jpg)
![archive2](https://f.cloud.github.com/assets/538411/1502192/3dd7e392-4897-11e3-9fbc-82ba82919262.jpg)

**Comment by nickvergessen** [comment]
This works fine for me.

**Comment by nachtelb** [comment]
Found it :) After new installation of the Extension it works fine with preset. If you turn "show categories" to "No" the Bug is scuttling.
