### ISSUE TITLE
Mention dependency in Readme

### ISSUE THREAD

**Issue by RobertHeim** [nickv-phpbb/phpbb-ext-newspage#82]
Hi,

it took me quite a while to find out that there is a dependency that is not included in the github repo, see https://www.phpbb.com/community/viewtopic.php?f=461&t=2256031

Could you provide that information in the Readme? Could save a lot of time for others.

**Comment by nickvergessen** [comment]
Well as mentioned in the topic, a release will contain the dependencies.
Stuff in this repo is not a release so dependencies are missing while tests and other stuff, not needed for production, is still present.
It is just not recommended to use the github source in a production board, but wait for a final release.

I'd better write that into the readme thou.

**Comment by RobertHeim** [comment]
you are totally right, but for a quick test of the extension its very easy to just clone it. This is ofc not recommended in a production environment, but for testing purposes its nice to get the hint from the readme.

**Comment by nickvergessen** [comment]
IIRC I tried to make it so you can run the extension without the dependency, but I will check that again.
