### ISSUE TITLE
Could use some events

### ISSUE THREAD

**Issue by PayBas** [nickv-phpbb/phpbb-ext-newspage#85]
We could use some events in here.

Particularly one somewhere inside the base() function: https://github.com/nickvergessen/phpbb-ext-newspage/blob/develop-ascraeus/newspage.php#L146

And a few template events, somewhere around these places:
https://github.com/nickvergessen/phpbb-ext-newspage/blob/develop-ascraeus/styles/prosilver/template/newspage_body.html#L4
https://github.com/nickvergessen/phpbb-ext-newspage/blob/develop-ascraeus/styles/prosilver/template/newspage_body.html#L26
https://github.com/nickvergessen/phpbb-ext-newspage/blob/develop-ascraeus/styles/prosilver/template/newspage_body.html#L178
https://github.com/nickvergessen/phpbb-ext-newspage/blob/develop-ascraeus/styles/prosilver/template/newspage_body.html#L197

**Comment by nickvergessen** [comment]
As for base() can you tell what exactly you are aiming for?

**Comment by PayBas** [comment]
Basically I just need an event in base() to include the Recent Topics extension on the page. So for my particular use-case, the location inside base() doesn't matter (nor do the dispatched $vars).

But I'm sure you can think of a situation or other extension that might want to manipulate the SQL query, or template vars, or whatever.
