### ISSUE TITLE
Rename "core" template events to proper vendor template events

### ISSUE THREAD

**Issue by PayBas** [nickv-phpbb/phpbb-ext-newspage#86]
Apparently it's the validation policy ;).

`viewtopic_body_postrow_custom_fields_before` etc

**Comment by nickvergessen** [comment]
well this is the exact copy of a core event since I copied the `viewtopic_body.html`
but will think about it

**Comment by PayBas** [comment]
Yeah, I did the exact same thing with the Recent Topics extension. But apparently, some ext authors find this annoying because it can lead to unexpected behavior.
https://www.phpbb.com/community/viewtopic.php?f=456&t=2236571&start=120#p13884466

**Comment by PayBas** [comment]
Apparently, it's not necessary according to the ext team ;)

https://www.phpbb.com/community/viewtopic.php?f=456&t=2236571&start=135#p13915421
