### ISSUE TITLE
phpBB 3.1.2 - NEWS_CHAR_LIMIT - does not work

### ISSUE THREAD

**Issue by Galixte** [nickv-phpbb/phpbb-ext-newspage#88]
Hi,
- the limit of chars of news (Shorten news text) does not work.
- also, the feature "Show moved topics" does not work.
- also, the feature "The settings have been saved successfully." does not displayed.

**Comment by nickvergessen** [comment]
Did you download the extension from github?

**Comment by Galixte** [comment]
Yes :)

**Comment by nickvergessen** [comment]
Well then you need to set up the dependencies:
https://github.com/nickvergessen/phpbb-ext-newspage#development-installation

**Comment by Galixte** [comment]
After the set up the dependencies, it's OK for this :
- the limit of chars of news (Shorten news text) does not work.

But those problems are not fixed :
- the feature "Show moved topics" does not work.
- the feature "The settings have been saved successfully." does not displayed.

**Comment by Galixte** [comment]
@nickvergessen,

could you take a look about the last problems ?

**Comment by nickvergessen** [comment]
Fixed both issues

**Comment by Galixte** [comment]
Hi @nickvergessen,

when i update the settings, i don’t see the message: “The settings have been saved successfully.”.

Also, after update the settings, the refresh of the page doesn’t work.

**Comment by nickvergessen** [comment]
That will be fixed with phpBB 3.1.5 ;) nothing this extension can do about:
https://github.com/phpbb/phpbb/pull/3601/files

**Comment by Galixte** [comment]
Hi,

thanks for information !
