### ISSUE TITLE
nickvergessen/phpbb-tool-trimmessage dependency missing from download

### ISSUE THREAD

**Issue by David-NF** [nickv-phpbb/phpbb-ext-newspage#90]
The option to change the number of characters in a news message has no effect. Could it be that this function is not working? I tried different values but it has no effect...

A user on phpbb.nl noticed it, when I tested it I noticed the same.

Source: http://www.phpbb.nl/forums/viewtopic.php?f=93&t=59796

**Comment by nickvergessen** [comment]
Duplicate of #88 

Basically the problem is, that there has been no release so far :P

**Comment by David-NF** [comment]
Thanks, I know... they know they shouldn't use extensions in dev but sometimes they try anyway ;) Just wanted to be sure you where aware of this issue. Didn't look at the closed issues, only the open en PR, sorry for the inconvenience.

**Comment by nickvergessen** [comment]
I think I will just commit the vendor folder for the time being since I decide whether I want to submit a package to the database

**Comment by Galixte** [comment]
Hi,

"The option to change the number of characters in a news message" it works since i set up the dependencies :
https://github.com/nickvergessen/phpbb-ext-newspage#development-installation
